[package]
name = "snow-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
snow-media = { path = "../snow-media" }
crossbeam-channel.workspace = true
smallvec.workspace = true


[dev-dependencies]
proptest = "1.11.0"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_System_Performance",
] }

[target.'cfg(target_os = "macos")'.dependencies]
rayon.workspace = true
