// Generated by tools/generate_icon_pack.py. DO NOT EDIT.
#ifndef ADQT_GENERATED_SNOW_SHOT_SNOWSHOTICONS_H
#define ADQT_GENERATED_SNOW_SHOT_SNOWSHOTICONS_H

#include "external_icon_pack.h"

namespace snow_shot::presentation::icons::custom {

const adqt::icons::ExternalIconPack& pack();
adqt::icons::IconPackRegistrationResult registerWith(adqt::icons::IconRenderer& renderer);
adqt::icons::IconPackRegistrationResult ensureRegistered();

namespace app {
[[nodiscard]] adqt::icons::IconRef ApplicationIcon(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ApplicationTitleBarIcon(const adqt::icons::IconColors& colors = {});
} // namespace app

namespace brand {
[[nodiscard]] adqt::icons::IconRef SnowShotLogo(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SnowShotMiniLogo(const adqt::icons::IconColors& colors = {});
} // namespace brand

namespace outlined {
[[nodiscard]] adqt::icons::IconRef AlignBottom(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
AlignCenterHorizontal(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AlignCenterVertical(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AlignLeft(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AlignRight(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AlignTop(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Angle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowRatio(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowShaftPlain(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowShaftTapered(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowTypeCurved(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowTypeElbow(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowTypeStraight(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadBar(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadBarStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadCircle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCircleOutline(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCircleOutlineStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadCircleStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCrowfootMany(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCrowfootManyStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadCrowfootOne(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCrowfootOneOrMany(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCrowfootOneOrManyStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadCrowfootOneStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadDiamond(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadDiamondOutline(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadDiamondOutlineStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadDiamondStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadDot(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadDotStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadIndentedTriangle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadIndentedTriangleStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadNone(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadNoneStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadStandard(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadStandardStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ArrowheadTriangle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadTriangleOutline(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadTriangleOutlineStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ArrowheadTriangleStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AutoScroll(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef AutoScrollInterval(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Blur(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ColorPicker(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Delete(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef DestroyPinnedWindow(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Disabled(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef DistributeHorizontal(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef DistributeVertical(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Duplicate(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Exit(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ExportConfiguration(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ExportSettings(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FillSolid(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FlipVertical(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FontSizeLarge(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FontSizeMedium(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FontSizeSmall(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FontSizeVeryLarge(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef FullScreenCanvas(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Group(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Html(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ImportConfiguration(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef JumpTranslate(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Keyboard(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef LaserPointer(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef LineTypeCurved(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef LineTypeStraight(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef LogicalPixels(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef MagicWand(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Markdown(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Mouse(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
MoveSelectionHorizontal(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
MoveSelectionVertical(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef OcrTranslate(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Opacity(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef PhysicalPixels(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef PinClipboard(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef PinToScreen(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
PinToScreenManagement(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef QuickSave(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordScreen(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecorderDelay(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingClick(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingCursor(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingFolder(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingKeyboard(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingMicrophone(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
RecordingPostProcessing(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingRender(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
RecordingRenderSettings(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingResume(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingStart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RecordingStop(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef RefreshCapture(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Restart(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Save(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScanQrcode(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScreenshotCopy(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScreenshotDelay(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotFocusedWindow(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScreenshotFullScreen(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScreenshotRegionAdd(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotRegionCurved(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotRegionFreehand(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotRegionPolyline(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotRegionRectangle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
ScreenshotRegionReduce(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScrollingHorizontal(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScrollingScreenshot(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ScrollingVertical(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Select(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SelectionLockAspect(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SelectionRadius(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SelectionShadow(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SequenceNumberCircle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
SequenceNumberOutlinedCircle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
SequenceNumberOutlinedSquare(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
SequenceNumberSolidCircle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef
SequenceNumberSolidSquare(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ShapeDiamond(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ShapeEllipse(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ShapeRectangle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef TableRecognition(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef TextRecognition(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolArrow(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolEraser(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolFilter(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolFreeDraw(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolHighlight(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolLine(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolMove(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolRecognizeText(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolRectangle(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolSelect(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolSerialNumber(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolSpotlight(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolText(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef ToolWatermark(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Trash(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef WatermarkGap(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef WheelMouse(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef Window(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef WindowGroupSwitch(const adqt::icons::IconColors& colors = {});
} // namespace outlined

namespace twotone {
[[nodiscard]] adqt::icons::IconRef ScreenshotFeature(const adqt::icons::IconColors& colors = {});
} // namespace twotone

} // namespace snow_shot::presentation::icons::custom

#endif // ADQT_GENERATED_SNOW_SHOT_SNOWSHOTICONS_H
