[package]
name = "snow-recording-export"
version = "0.1.0"
edition = "2024"
license.workspace = true
build = "build.rs"

[features]
bench-timing = []
bench-experiments = []

[dependencies]
snow-core = { path = "../snow-core" }
snow-audio-recorder = { path = "../snow-audio-recorder" }
snow-recording-model = { path = "../snow-recording-model" }
snow-recording-effects = { path = "../snow-recording-effects" }
bincode.workspace = true
crossbeam-channel.workspace = true
ffmpeg-next.workspace = true
rayon.workspace = true
num_cpus.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
zstd.workspace = true
uuid.workspace = true
snow-media = { path = "../snow-media" }

[target.'cfg(windows)'.dependencies]
snow-d3d11 = { path = "../snow-d3d11" }
windows = { workspace = true, features = ["Win32_Graphics_Direct3D11"] }

[dev-dependencies]
gif = "0.14.2"
anyhow.workspace = true
proptest = "1.11.0"
symphonia = { version = "0.5.4", default-features = false, features = ["aac", "isomp4"] }

[target.'cfg(windows)'.dev-dependencies]
windows = { workspace = true, features = [
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }

[target.'cfg(target_os = "macos")'.dev-dependencies]
snow-macos = { path = "../snow-macos" }
