[package]
name = "snow-shot-rust-ffi"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
snow-core = { path = "../snow-crates/crates/snow-core" }
snow-visual-region-detector-c = { path = "../snow-crates/crates/snow-visual-region-detector-c" }
snow-recording-effects-c = { path = "../snow-crates/crates/snow-recording-effects-c" }
snow-diagnostics = { path = "../snow-crates/crates/snow-diagnostics" }
snow-recording-c = { path = "../snow-crates/crates/snow-recording-c" }
snow-capture-c = { path = "../snow-crates/crates/snow-capture-c" }
snow-draw-engine-c = { path = "../snow_draw_engine_qt/crates/snow-draw-engine-c" }
snow-stitch-images-c = { path = "../snow-crates/crates/snow-stitch-images-c" }
snow-selected-text-c = { path = "../snow-crates/crates/snow-selected-text-c", optional = true }

[target.'cfg(any(windows, target_os = "macos"))'.dependencies]
snow-ui-selector-c = { path = "../snow-crates/crates/snow-ui-selector-c" }

[features]
perf-instrumentation = ["snow-stitch-images-c/perf-instrumentation"]
selected-text = ["dep:snow-selected-text-c"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
debug = 2
incremental = false
overflow-checks = false

[profile.release-fast]
inherits = "release"
opt-level = 2
codegen-units = 16
lto = "thin"
incremental = true
