[package]
name = "snow-stitch-images-c"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
snow-core = { path = "../snow-core" }
png.workspace = true
snow-stitch-images = { path = "../snow-stitch-images", default-features = false }
tempfile.workspace = true

[features]
perf-instrumentation = ["snow-stitch-images/perf-instrumentation"]
