set(SNOW_CANVAS_QT_PRIVATE_SOURCE_DIRS
    src
    src/core
    src/rendering
    src/text
    src/widget
)

set(SNOW_CANVAS_QT_SOURCES
    src/rendering/snow_canvas_path_geometry.cpp
    include/snow_draw_engine_qt/snow_canvas_path_geometry.h
    src/core/snow_canvas_changed_viewports.cpp
    src/core/snow_canvas_changed_viewports.h
    src/core/snow_canvas_commands.cpp
    src/core/snow_canvas_commands.h
    src/core/snow_canvas_cursor_controller.cpp
    src/core/snow_canvas_cursor_controller.h
    src/core/snow_canvas_element_id.h
    src/core/snow_canvas_event_flow.cpp
    src/core/snow_canvas_event_flow.h
    src/core/snow_canvas_ffi_handles.h
    src/core/snow_canvas_input_adapter.cpp
    src/core/snow_canvas_input_adapter.h
    src/core/snow_canvas_interaction.cpp
    src/core/snow_canvas_interaction.h
    src/core/snow_canvas_lifecycle.cpp
    src/core/snow_canvas_lifecycle.h
    src/core/snow_canvas_runtime.cpp
    src/core/snow_canvas_runtime_access.h
    src/core/snow_canvas_runtime_clients.cpp
    src/core/snow_canvas_runtime_clients.h
    src/core/snow_canvas_runtime_session.cpp
    src/core/snow_canvas_runtime_session.h
    src/core/snow_canvas_runtime_thread_affinity.cpp
    src/core/snow_canvas_runtime_thread_affinity.h
    src/core/snow_canvas_state.cpp
    src/core/snow_canvas_state.h
    src/core/snow_canvas_sync_plan.cpp
    src/core/snow_canvas_sync_plan.h
    src/core/snow_canvas_type_conversions.cpp
    src/core/snow_canvas_type_conversions.h
    src/core/snow_canvas_utf8.cpp
    src/core/snow_canvas_utf8.h
    src/core/snow_canvas_viewport.cpp
    src/core/snow_canvas_viewport.h
    src/rendering/snow_canvas_compositor.cpp
    src/rendering/snow_canvas_compositor.h
    src/rendering/snow_canvas_custom_renderer.cpp
    src/rendering/snow_canvas_reference_scene.cpp
    src/rendering/snow_canvas_reference_scene.h
    src/rendering/snow_canvas_display_cache.cpp
    src/rendering/snow_canvas_display_cache.h
    src/rendering/snow_canvas_display_item.cpp
    src/rendering/snow_canvas_display_item.h
    src/rendering/snow_canvas_export.cpp
    src/rendering/snow_canvas_export.h
    src/rendering/snow_canvas_smart_erase.cpp
    src/rendering/snow_canvas_smart_erase_algorithm.cpp
    src/rendering/snow_canvas_filter_render.cpp
    src/rendering/snow_canvas_filter_tile_cache.cpp
    src/rendering/snow_canvas_filter_render.h
    src/rendering/snow_canvas_region_filter.cpp
    src/rendering/snow_canvas_pen_mask_atlas.cpp
    src/rendering/snow_canvas_pen_mask_atlas.h
    src/rendering/snow_canvas_pen_mask_avx2.cpp
    src/rendering/snow_canvas_pen_mask_avx2.h
    src/rendering/snow_canvas_filter_avx2.cpp
    src/rendering/snow_canvas_filter_avx2.h
    src/rendering/snow_canvas_fill_render.cpp
    src/rendering/snow_canvas_fill_render.h
    src/rendering/snow_canvas_render_diagnostics.cpp
    src/rendering/snow_canvas_render_diagnostics.h
    src/rendering/snow_canvas_render_geometry.cpp
    src/rendering/snow_canvas_render_geometry.h
    src/rendering/snow_canvas_renderer.cpp
    src/rendering/snow_canvas_render_plan.h
    src/rendering/snow_canvas_renderer.h
    src/rendering/snow_canvas_spotlight_renderer.cpp
    src/rendering/snow_canvas_spotlight_renderer.h
    src/rendering/snow_canvas_watermark_renderer.cpp
    src/rendering/snow_canvas_watermark_renderer.h
    src/text/snow_canvas_text.cpp
    src/text/snow_canvas_text.h
    src/text/snow_canvas_text_draft.cpp
    src/text/snow_canvas_text_draft.h
    src/text/snow_canvas_text_edit_geometry.cpp
    src/text/snow_canvas_text_edit_geometry.h
    src/text/snow_canvas_text_edit_target.cpp
    src/text/snow_canvas_text_edit_target.h
    src/text/snow_canvas_text_editor_connector.cpp
    src/text/snow_canvas_text_editor_connector.h
    src/text/snow_canvas_text_editor_input.cpp
    src/text/snow_canvas_text_editor_input.h
    src/text/snow_canvas_text_editor_overlay.cpp
    src/text/snow_canvas_text_editor_overlay.h
    src/text/snow_canvas_text_editor_session.cpp
    src/text/snow_canvas_text_editor_session.h
    src/text/snow_canvas_text_editor_view.cpp
    src/text/snow_canvas_text_editor_view.h
    src/text/snow_canvas_text_layout.cpp
    src/text/snow_canvas_text_layout.h
    src/text/snow_canvas_text_measurement.cpp
    src/text/snow_canvas_text_measurement.h
    src/text/snow_canvas_text_render.cpp
    src/text/snow_canvas_text_render.h
    src/widget/snow_canvas_widget.cpp
    src/widget/snow_canvas_widget_display_state.cpp
    src/widget/snow_canvas_widget_display_state.h
    src/widget/snow_canvas_widget_input_handler.cpp
    src/widget/snow_canvas_widget_input_handler.h
    src/widget/snow_canvas_widget_keyboard_flow.cpp
    src/widget/snow_canvas_widget_keyboard_flow.h
    src/widget/snow_canvas_widget_paint_frame.cpp
    src/widget/snow_canvas_widget_paint_frame.h
    src/widget/snow_canvas_widget_pointer_flow.cpp
    src/widget/snow_canvas_widget_pointer_flow.h
    src/widget/snow_canvas_widget_repaint.cpp
    src/widget/snow_canvas_widget_repaint.h
    src/widget/snow_canvas_widget_runtime_binding.cpp
    src/widget/snow_canvas_widget_runtime_binding.h
    src/widget/snow_canvas_widget_selection_hit_testing.cpp
    src/widget/snow_canvas_widget_selection_hit_testing.h
    src/widget/snow_canvas_widget_sync.cpp
    src/widget/snow_canvas_widget_sync.h
    src/widget/snow_canvas_widget_text_interaction.cpp
    src/widget/snow_canvas_widget_text_interaction.h
    include/snow_draw_engine_qt/snow_canvas_export_types.h
    include/snow_draw_engine_qt/snow_canvas_custom_renderer.h
    include/snow_draw_engine_qt/snow_canvas_region_filter.h
    include/snow_draw_engine_qt/snow_canvas_runtime.h
    include/snow_draw_engine_qt/snow_canvas_types.h
    include/snow_draw_engine_qt/snow_canvas_style_edit.h
    include/snow_draw_engine_qt/snow_canvas_widget.h
)
