function(snow_strip_pkg_config_apple_framework_options out_options)
    set(_remaining ${ARGN})
    set(_sanitized)
    while(_remaining)
        list(POP_FRONT _remaining _option)
        if(_option STREQUAL "-framework")
            if(NOT _remaining)
                message(FATAL_ERROR "pkg-config returned -framework without a framework name")
            endif()
            list(POP_FRONT _remaining _framework)
            if(_framework MATCHES "^-")
                message(FATAL_ERROR
                    "pkg-config returned an invalid Apple framework name: ${_framework}")
            endif()
        else()
            list(APPEND _sanitized "${_option}")
        endif()
    endwhile()
    set(${out_options} "${_sanitized}" PARENT_SCOPE)
endfunction()
